[tasks.upgradesys]
description = "upgrade global tools (pyclibase)"
run = '''
# upgrade global
echo "## apt"
LANG=C sudo apt update
LANG=C sudo apt upgrade
LANG=C sudo apt autoremove -y
echo "## mise"
mise self-update
mise up
echo "## uv"
uv tool upgrade --all
'''
alias = "upsys"

[tasks.upgradelocal]
description = "upgrade in this project"
run = '''
# upgrade this project
echo "## rm uv.lock"
rm uv.lock
echo "## uv sync"
uv sync
echo "## pip"
uv pip install -U --group dev -e .
echo "## uv run pyclibase -V"
uv run pyclibase -V
'''
alias = "uplocal"
depends = ["upgradesys"]

[tasks.lint]
description = "linting"
run = '''
# linting
echo "## isort"
uv run isort src tests samples
echo "## ruff"
uv run ruff format src tests samples
echo "## pyright"
uv run pyright src tests samples
echo "## mypy"
uv run mypy src tests samples
'''
depends = ["upgradelocal"]

[tasks.test]
description = "test"
run = "uv run pytest -v tests"
depends = ["lint"]

[tasks.install]
description = "install editable"
run = '''
# Install
echo "## Install"
uv pip install -e .
echo "## version"
uv run pyclibase -V
'''
depends = ["test"]
