[tasks.upgradesys]
description = "upgrade global tools"
run = '''
# upgrade global
echo "# apt"
LANG=C sudo apt update
LANG=C sudo apt upgrade
LANG=C sudo apt autoremove -y
echo "# mise"
mise self-update
mise up
echo "# uv"
uv tool upgrade --all
'''
alias = "upsys"

[tasks.upgradelocal]
description = "upgrade in this project"
run = '''
# upgrade this project
echo "# pip"
uv pip install -U --group dev -e .
'''
alias = "uplocal"
depends = ["upgradesys"]

[tasks.lint]
description = "linting"
run = '''
# linting
echo "# isort"
uv run isort src tests samples
echo "# ruff"
uv run ruff format src tests samples
echo "# pyright"
uv run pyright src tests samples
echo "# flake8"
uv run flake8 src tests samples
echo "# mypy"
uv run mypy src tests samples
'''
depends = ["upgradelocal"]

[tasks.test]
description = "test"
run = "uv run pytest -v tests"

[tasks.install]
description = "install editable"
run = '''
# Install
uv pip install -e .
uv run pyclibase -V
'''
depends = ["lint"]
